configuration:
  backupStorageLocation:
  - bucket: goodtoknow123
    provider: aws
  volumeSnapshotLocation:
  - config:
      region: us-east-1
    provider: aws
initContainers:
- name: velero-plugin-for-aws
  image: velero/velero-plugin-for-aws:v1.7.1
  volumeMounts:
  - mountPath: /target
    name: plugins
credentials:
  useSecret: false
serviceAccount:
  server:
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::887998956998:role/eks-velero-role"